"""empty message

Revision ID: 53a8d8129242
Revises: 5b3f569a4eac
Create Date: 2019-12-26 16:50:20.587715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53a8d8129242'
down_revision = '5b3f569a4eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gname', sa.String(length=80), nullable=True),
    sa.Column('gtype', sa.String(length=2), nullable=True),
    sa.Column('gprice', sa.String(length=5), nullable=True),
    sa.Column('gage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gname')
    )
    op.drop_index('gname', table_name='goods')
    op.drop_table('goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gname', mysql.VARCHAR(collation='utf8_bin', length=80), nullable=True),
    sa.Column('gtype', mysql.VARCHAR(collation='utf8_bin', length=2), nullable=True),
    sa.Column('gprice', mysql.VARCHAR(collation='utf8_bin', length=5), nullable=True),
    sa.Column('gage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('gname', 'goods', ['gname'], unique=True)
    op.drop_table('p_goods')
    # ### end Alembic commands ###
