"""empty message

Revision ID: 5b3f569a4eac
Revises: 
Create Date: 2019-12-26 16:46:23.179578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3f569a4eac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gname', sa.String(length=80), nullable=True),
    sa.Column('gtype', sa.String(length=2), nullable=True),
    sa.Column('gprice', sa.String(length=5), nullable=True),
    sa.Column('gage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
